train:
    model_parameters:
        learning_rate: 0.0001
        batch_size: 16
        epochs: 5
        linear_1_size: 1024
        linear_2_size: 512
        seed: 1234
        log_model: True
optimize_hyperparameters:
    sweep_parameters:
        method: random
        metric:
            name: loss
            goal: minimize
        parameters:
            linear_1_size:
                value: 1024
            linear_2_size: 
                values: [128, 256, 512]
            learning_rate: 
                min: 0.00001
                max: 0.01
            batch_size: 
                distribution: int_uniform
                min: 2
                max: 32
            epochs:
                value: 5
            seed: 
                value: 1234
            log_model: 
                value: False
    count: 5